export const referenceData = [
  {
    example:
      'Fritsch, M. and Schroeter, A. (2011) \u2018Why does the effect of new business formation differ across regions?\u2019, <em>Small Business Economics: An Entrepreneurship Journal</em>, 36(4), pp. 383-400.',
    fields: [
      {
        italic: false,
        label: 'Author(s) (surname or family name before initials)',
        placeholder: 'Fritsch, M. and Schroeter, A.',
        prefix: '',
        required: true,
        suffix: ' ',
        type: 'text',
        uuid: '665224b0065b758a1bf4d1ba',
      },
      {
        italic: false,
        label: ' Year of publication',
        placeholder: '2011',
        prefix: '(',
        required: true,
        suffix: ') ',
        type: 'number',
        uuid: '665224d1065b758a1bf4d1bb',
      },
      {
        italic: false,
        label: 'Title of the article',
        placeholder:
          'Why does the effect of new business formation differ across regions?',
        prefix: "'",
        required: true,
        suffix: "', ",
        type: 'text',
        uuid: '665224f7065b758a1bf4d1bc',
      },
      {
        italic: true,
        label: 'Title of journal',
        placeholder: 'Small Business Economics: An Entrepreneurship Journal',
        prefix: '',
        required: true,
        suffix: ', ',
        type: 'text',
        uuid: '66522546065b758a1bf4d1bd',
      },
      {
        italic: false,
        label: 'Volume',
        placeholder: '36',
        prefix: '',
        required: true,
        suffix: '',
        type: 'text',
        uuid: '66522599065b758a1bf4d1be',
      },
      {
        italic: false,
        label: 'Part number',
        placeholder: '4',
        prefix: '(',
        required: true,
        suffix: '), ',
        type: 'text',
        uuid: '665225b0065b758a1bf4d1bf',
      },
      {
        italic: false,
        label: 'Page numbers',
        placeholder: 'pp. 383-400',
        prefix: '',
        required: true,
        suffix: '. ',
        type: 'text',
        uuid: '665225d1065b758a1bf4d1c0',
      },
    ],
    name: 'Journal article (printed)',
    uuid: '66522625065b758a1bf4d1c1',
  },
  {
    example:
      'Chandler, D. (2001) <em>Semiotics for beginners.</em> Available at: http://www.aber.ac.uk/media/Documents/S4B/sem02.html (Accessed: 26 July 2010). \n',
    fields: [
      {
        italic: false,
        label: 'Author(s) (surname or family name before initials)',
        placeholder: 'Fritsch, M. and Schroeter, A.',
        prefix: '',
        required: true,
        suffix: ' ',
        type: 'text',
        uuid: '665224b0065b758a1bf4d1ba',
      },
      {
        italic: false,
        label: 'Year that the site was published/last updated',
        placeholder: '2001',
        prefix: '(',
        required: true,
        suffix: ') ',
        type: 'number',
        uuid: '66adbe33ff98862f92d7b51e',
      },
      {
        italic: true,
        label: 'Title of Internet site',
        placeholder: 'Semiotics for beginners.',
        prefix: '',
        required: true,
        suffix: ' ',
        type: 'text',
        uuid: '66adbe5fff98862f92d7b51f',
      },
      {
        italic: false,
        label: 'Available at URL',
        placeholder: 'http://www.aber.ac.uk/media/Documents/S4B/sem02.html',
        prefix: 'Available at: ',
        required: true,
        suffix: ' ',
        type: 'url',
        uuid: '66adbf1bff98862f92d7b520',
      },
      {
        dateFormat: 'ddMMMMyyyy',
        italic: false,
        label: 'Accessed date',
        placeholder: '2024-08-03',
        prefix: '(Accessed: ',
        required: true,
        suffix: '). ',
        type: 'date',
        uuid: '66adbf89ff98862f92d7b521',
      },
    ],
    name: 'Web pages with individual authors ',
    uuid: '66adc003ff98862f92d7b522',
  },
  {
    example:
      'Unison (2014) <em>NHS workers deserve fair pay.</em> Available at:\nhttp://www.unison.org.uk/at-work/health-care/keyissues/nhs-pay/home/ (Accessed: 17 December 2014).',
    fields: [
      {
        italic: false,
        label: ' Organisation as author',
        placeholder: 'Unison',
        prefix: '',
        required: true,
        suffix: ' ',
        type: 'text',
        uuid: '66adc203ff98862f92d7b523',
      },
      {
        italic: false,
        label: 'Year that the site was published/last updated',
        placeholder: '2001',
        prefix: '(',
        required: true,
        suffix: ') ',
        type: 'number',
        uuid: '66adbe33ff98862f92d7b51e',
      },
      {
        italic: true,
        label: 'Title of Internet site',
        placeholder: 'Semiotics for beginners.',
        prefix: '',
        required: true,
        suffix: ' ',
        type: 'text',
        uuid: '66adbe5fff98862f92d7b51f',
      },
      {
        italic: false,
        label: 'Available at URL',
        placeholder: 'http://www.aber.ac.uk/media/Documents/S4B/sem02.html',
        prefix: 'Available at: ',
        required: true,
        suffix: ' ',
        type: 'url',
        uuid: '66adbf1bff98862f92d7b520',
      },
      {
        dateFormat: 'ddMMMMyyyy',
        italic: false,
        label: 'Accessed date',
        placeholder: '2024-08-03',
        prefix: '(Accessed: ',
        required: true,
        suffix: '). ',
        type: 'date',
        uuid: '66adbf89ff98862f92d7b521',
      },
    ],
    name: 'Web pages with organisations as authors',
    uuid: '66adc256ff98862f92d7b524',
  },
  {
    example:
      '<em>Online Abertillery</em> (2010) Available at: http://www.abertillery.net/tales_ghost.html (Accessed: 19 July 2010).',
    fields: [
      {
        italic: true,
        label: 'Title of Internet site',
        placeholder: 'Semiotics for beginners.',
        prefix: '',
        required: true,
        suffix: ' ',
        type: 'text',
        uuid: '66adbe5fff98862f92d7b51f',
      },
      {
        italic: false,
        label: 'Year that the site was published/last updated',
        placeholder: '2001',
        prefix: '(',
        required: true,
        suffix: ') ',
        type: 'number',
        uuid: '66adbe33ff98862f92d7b51e',
      },
      {
        italic: false,
        label: 'Available at URL',
        placeholder: 'http://www.aber.ac.uk/media/Documents/S4B/sem02.html',
        prefix: 'Available at: ',
        required: true,
        suffix: ' ',
        type: 'url',
        uuid: '66adbf1bff98862f92d7b520',
      },
      {
        dateFormat: 'ddMMMMyyyy',
        italic: false,
        label: 'Accessed date',
        placeholder: '2024-08-03',
        prefix: '(Accessed: ',
        required: true,
        suffix: '). ',
        type: 'date',
        uuid: '66adbf89ff98862f92d7b521',
      },
    ],
    name: 'Web pages with no authors ',
    uuid: '66adc29aff98862f92d7b525',
  },
  {
    example:
      'Shah, V. (2011) \u2018Thought economics\u2019, <em>Thought Economics</em>, 6 July. Available at: http://thoughteconomics.blogspot.com/ (Accessed: 13 July 2011).\n',
    fields: [
      {
        italic: false,
        label: 'Author(s) (surname or family name before initials)',
        placeholder: 'Fritsch, M. and Schroeter, A.',
        prefix: '',
        required: true,
        suffix: ' ',
        type: 'text',
        uuid: '665224b0065b758a1bf4d1ba',
      },
      {
        italic: false,
        label: 'Year that the site was published/last updated',
        placeholder: '2001',
        prefix: '(',
        required: true,
        suffix: ') ',
        type: 'number',
        uuid: '66adbe33ff98862f92d7b51e',
      },
      {
        italic: false,
        label: 'Title of message',
        placeholder: 'Thought economics',
        prefix: "'",
        required: true,
        suffix: "', ",
        type: 'text',
        uuid: '66adc33eff98862f92d7b526',
      },
      {
        italic: true,
        label: 'Title of blog site',
        placeholder: 'Thought economics',
        prefix: '',
        required: true,
        suffix: ', ',
        type: 'text',
        uuid: '66adc3fcff98862f92d7b528',
      },
      {
        dateFormat: 'ddMMMM',
        italic: false,
        label: 'Day / Month of posted message',
        placeholder: '2024-08-03',
        prefix: '',
        required: true,
        suffix: '. ',
        type: 'date',
        uuid: '66adc3b9ff98862f92d7b527',
      },
      {
        italic: false,
        label: 'Available at URL',
        placeholder: 'http://www.aber.ac.uk/media/Documents/S4B/sem02.html',
        prefix: 'Available at: ',
        required: true,
        suffix: ' ',
        type: 'url',
        uuid: '66adbf1bff98862f92d7b520',
      },
      {
        dateFormat: 'ddMMMMyyyy',
        italic: false,
        label: 'Accessed date',
        placeholder: '2024-08-03',
        prefix: '(Accessed: ',
        required: true,
        suffix: '). ',
        type: 'date',
        uuid: '66adbf89ff98862f92d7b521',
      },
    ],
    name: 'Blogs',
    uuid: '66adc487ff98862f92d7b529',
  },
  {
    example:
      'Persensky, J., Lewis, P. and O\u2019Hara, J. (2005) \u2018Insights into the role of the operator in advanced reactors\u2019, <em>American Nuclear Society, Winter Meeting</em>, Washington D.C, 13-17 November. New York: Brookhaven National Laboratory. Available at: http://www.bnl.gov/isd/documents/30546.pdf (Accessed: 26 July 2010).\n',
    fields: [
      {
        italic: false,
        label: 'Author(s) (surname or family name before initials)',
        placeholder: 'Fritsch, M. and Schroeter, A.',
        prefix: '',
        required: true,
        suffix: ' ',
        type: 'text',
        uuid: '665224b0065b758a1bf4d1ba',
      },
      {
        italic: false,
        label: ' Year of publication',
        placeholder: '2011',
        prefix: '(',
        required: true,
        suffix: ') ',
        type: 'number',
        uuid: '665224d1065b758a1bf4d1bb',
      },
      {
        italic: false,
        label: 'Title of paper',
        placeholder:
          'Insights into the role of the operator in advanced reactors',
        prefix: "'",
        required: true,
        suffix: "', ",
        type: 'text',
        uuid: '66adc538ff98862f92d7b52a',
      },
      {
        italic: true,
        label: 'Title of conference: subtitle',
        placeholder: 'American Nuclear Society, Winter Meeting',
        prefix: '',
        required: true,
        suffix: ', ',
        type: 'text',
        uuid: '66adc595ff98862f92d7b52b',
      },
      {
        italic: false,
        label: 'Publisher',
        placeholder: 'New York: Brookhaven National Laboratory',
        prefix: '',
        required: true,
        suffix: '. ',
        type: 'text',
        uuid: '66adc61cff98862f92d7b52d',
      },
      {
        italic: false,
        label: 'Location and date of conference',
        placeholder: 'Washington D.C, 13-17 November',
        prefix: '',
        required: true,
        suffix: '. ',
        type: 'text',
        uuid: '66adc5e7ff98862f92d7b52c',
      },
      {
        italic: false,
        label: 'Available at URL',
        placeholder: 'http://www.aber.ac.uk/media/Documents/S4B/sem02.html',
        prefix: 'Available at: ',
        required: true,
        suffix: ' ',
        type: 'url',
        uuid: '66adbf1bff98862f92d7b520',
      },
      {
        dateFormat: 'ddMMMMyyyy',
        italic: false,
        label: 'Accessed date',
        placeholder: '2024-08-03',
        prefix: '(Accessed: ',
        required: true,
        suffix: '). ',
        type: 'date',
        uuid: '66adbf89ff98862f92d7b521',
      },
    ],
    name: 'Conference paper published on the Internet',
    uuid: '66adc669ff98862f92d7b52e',
  },
  {
    example:
      'Langhammer, B. and Stanghelle, J.K. (2009) \u2018Exercise on a treadmill or walking outdoors\u2019, <em>Clinical Rehabilitation</em>, 24(1), pp. 46-54. Available at: http://cre.sagepub.com (Accessed: 15 July 2010).',
    fields: [
      {
        italic: false,
        label: 'Author(s) (surname or family name before initials)',
        placeholder: 'Fritsch, M. and Schroeter, A.',
        prefix: '',
        required: true,
        suffix: ' ',
        type: 'text',
        uuid: '665224b0065b758a1bf4d1ba',
      },
      {
        italic: false,
        label: ' Year of publication',
        placeholder: '2011',
        prefix: '(',
        required: true,
        suffix: ') ',
        type: 'number',
        uuid: '665224d1065b758a1bf4d1bb',
      },
      {
        italic: false,
        label: 'Title of the article',
        placeholder:
          'Why does the effect of new business formation differ across regions?',
        prefix: "'",
        required: true,
        suffix: "', ",
        type: 'text',
        uuid: '665224f7065b758a1bf4d1bc',
      },
      {
        italic: true,
        label: 'Title of journal',
        placeholder: 'Small Business Economics: An Entrepreneurship Journal',
        prefix: '',
        required: true,
        suffix: ', ',
        type: 'text',
        uuid: '66522546065b758a1bf4d1bd',
      },
      {
        italic: false,
        label: 'Volume',
        placeholder: '36',
        prefix: '',
        required: true,
        suffix: '',
        type: 'text',
        uuid: '66522599065b758a1bf4d1be',
      },
      {
        italic: false,
        label: 'Issue',
        placeholder: '1',
        prefix: '(',
        required: false,
        suffix: '), ',
        type: 'text',
        uuid: '66adc714ff98862f92d7b52f',
      },
      {
        italic: false,
        label: 'Page numbers',
        placeholder: 'pp. 383-400',
        prefix: '',
        required: true,
        suffix: '. ',
        type: 'text',
        uuid: '665225d1065b758a1bf4d1c0',
      },
      {
        italic: false,
        label: 'Available at URL',
        placeholder: 'http://www.aber.ac.uk/media/Documents/S4B/sem02.html',
        prefix: 'Available at: ',
        required: true,
        suffix: ' ',
        type: 'url',
        uuid: '66adbf1bff98862f92d7b520',
      },
      {
        dateFormat: 'ddMMMMyyyy',
        italic: false,
        label: 'Accessed date',
        placeholder: '2024-08-03',
        prefix: '(Accessed: ',
        required: true,
        suffix: '). ',
        type: 'date',
        uuid: '66adbf89ff98862f92d7b521',
      },
    ],
    name: 'Journals found online or in databases',
    uuid: '66adc76eff98862f92d7b530',
  },
];